# -*- coding: utf-8 -*-
"""686.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFh6tL7-NpGJrcObaAtGCHZotCCv_T9J
"""

import pandas as pd
from sqlalchemy import create_engine
import pymysql
import matplotlib.pyplot as plt
import os

# AWS RDS MySQL Connection
AWS_HOST = 'soc-db-instance.clg6uiiq0hr9.us-east-1.rds.amazonaws.com'
AWS_USER = 'admin'
AWS_PASSWORD = 'syntaxsoldiers3'
AWS_DATABASE = 'soc_db'

# Create SQLAlchemy engine for AWS RDS
engine = create_engine(f'mysql+pymysql://{AWS_USER}:{AWS_PASSWORD}@{AWS_HOST}/{AWS_DATABASE}')

print("Connecting to AWS RDS MySQL Database...")
print(f"Host: {AWS_HOST}")
print(f"Database: {AWS_DATABASE}")

# Load tables from AWS RDS
employees = pd.read_sql_table('employees', engine)
departments = pd.read_sql_table('departments', engine)
incidents = pd.read_sql_table('incidents', engine)
alerts = pd.read_sql_table('alerts', engine)
assets = pd.read_sql_table('assets', engine)
detection_rules = pd.read_sql_table('detection_rules', engine)
incident_iocs = pd.read_sql_table('incident_iocs', engine)
iocs = pd.read_sql_table('iocs', engine)

print(f"Successfully loaded {len(alerts)} alerts from AWS RDS")

# Create charts directory
os.makedirs('charts', exist_ok=True)

# AWS RDS engine already created above - ready to use

# AWS RDS engine already created at the beginning

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def run_query(sql):
    return pd.read_sql(sql, engine)

# SQL queries removed for Q1, Q2, Q3 as they don't have corresponding charts

# Plotly/Colab code removed - using only Matplotlib charts below

# ==============================================================================
# Matplotlib Charts Section - Q5 through Q11
# ==============================================================================

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# ==============================================================================
# Q2: MTTD, MTTC, MTTR Analysis
# ==============================================================================
data = {
    'severity': ['low', 'medium', 'high', 'critical'],
    'mttd_hours': [1.5, 0.8, 0.2, 0.1],  # Mean Time To Detect
    'mttc_hours': [4.0, 2.5, 1.0, 0.5],  # Mean Time To Contain
    'mttr_hours': [8.2, 5.1, 3.5, 2.0]   # Mean Time To Resolve
}
df = pd.DataFrame(data)

# Reformat the data for easier plotting (melt the columns)
df_melt = df.melt('severity', var_name='Metric', value_name='Hours')

# Define a consistent ordering for the severity levels
severity_order = ['low', 'medium', 'high', 'critical']
df_melt['severity'] = pd.Categorical(df_melt['severity'], categories=severity_order, ordered=True)
df_melt = df_melt.sort_values('severity')


# ==============================================================================
# 3. Visualization using Matplotlib
# ==============================================================================

# Set up the plot area
fig, ax = plt.subplots(figsize=(10, 6))
plt.style.use('seaborn-v0_8-whitegrid')

# Define metric names and colors
metrics = ['mttd_hours', 'mttc_hours', 'mttr_hours']
metric_labels = ['MTTD (Detect)', 'MTTC (Contain)', 'MTTR (Resolve)']
colors = ['#1f77b4', '#ff7f0e', '#2ca02c'] # Blue, Orange, Green

# Define bar width and positions
bar_width = 0.25
r1 = np.arange(len(severity_order))

# Plot bars for each metric
for i, (metric, label, color) in enumerate(zip(metrics, metric_labels, colors)):
    # Get the values for the current metric, ensuring order is maintained
    values = df[metric]
    # Calculate bar positions (r1 + i*bar_width)
    r = [x + i * bar_width for x in r1]

    # Create the bar plot
    bars = ax.bar(r, values, color=color, width=bar_width, edgecolor='grey', label=label)

    # Add labels above the bars
    for bar in bars:
        yval = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2, yval + 0.1, round(yval, 1),
                ha='center', va='bottom', fontsize=9)

# Configure the chart aesthetics
ax.set_title('Mean Incident Response Times (in Hours) by Severity', fontsize=14, pad=20)
ax.set_ylabel('Average Time (Hours)', fontsize=12)
ax.set_xlabel('Incident Severity Level', fontsize=12)

# Set x-axis ticks to be centered beneath the groups of bars
ax.set_xticks([r + bar_width for r in range(len(severity_order))])
ax.set_xticklabels([s.capitalize() for s in severity_order])

ax.legend(title='Metric', loc='upper left', bbox_to_anchor=(1, 1))
ax.set_ylim(0, 10) # Set a consistent y-limit for better comparison

# Add grid lines for better readability
ax.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout(rect=[0, 0, 0.9, 1]) # Adjust layout for legend
plt.savefig('charts/q2_mttd_mttc_mttr.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q2: MTTD/MTTC/MTTR saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 3)
# This is the SQL logic that the data for the visualization is based on.
# ==============================================================================
"""
# Q3. Which threat actors (from threat intel mapping) are associated with the most incidents,
# and what are their primary motivations and sophistication levels?

SELECT
    ta.actor_id,
    ta.name AS threat_actor,
    ta.origin,
    ta.motivation,
    ta.sophistication,
    COUNT(DISTINCT ii.incident_id) AS incident_count
FROM threat_actors ta
LEFT JOIN incident_iocs ii
    ON ta.actor_id = ii.actor_id
LEFT JOIN incidents i
    ON ii.incident_id = i.incident_id
GROUP BY
    ta.actor_id, ta.name, ta.origin, ta.motivation, ta.sophistication
HAVING incident_count > 0
ORDER BY incident_count DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the new SQL query.
# ==============================================================================
data = {
    'threat_actor': ['Lazarus Group', 'ShadowBrokers', 'APT41', 'DarkTide', 'Fancy Bear', 'CyberVigil'],
    'motivation': ['Financial', 'Financial', 'Espionage', 'Financial', 'Espionage', 'Activism'],
    'sophistication': ['Critical', 'High', 'High', 'Medium', 'Medium', 'Low'],
    'incident_count': [150, 120, 95, 75, 60, 40]
}
df = pd.DataFrame(data)

# Define order for sophistication levels and map to a numerical scale
sophistication_order = ['Low', 'Medium', 'High', 'Critical']
soph_map = {level: i + 1 for i, level in enumerate(sophistication_order)}
df['soph_num'] = df['sophistication'].map(lambda x: soph_map.get(x, 0))

# Prepare colors and size for the Bubble Chart
# Scale the incident count for bubble size (s) for better visualization
max_count = df['incident_count'].max()
df['size'] = (df['incident_count'] / max_count) * 2000 + 100 # Scaling factor

# Map Motivation to distinct colors
motivation_colors = {
    'Financial': '#E377C2',  # Pink
    'Espionage': '#17BECF',  # Cyan
    'Activism': '#FF7F0E'    # Orange
}
df['color'] = df['motivation'].map(motivation_colors)


# ==============================================================================
# 3. Visualization using Matplotlib (Bubble Chart)
# ==============================================================================

# Set up the plot area
fig, ax = plt.subplots(figsize=(12, 7))

# Create the Bubble Chart (Scatter Plot)
scatter = ax.scatter(
    x=df['soph_num'],          # X-axis: Sophistication (Numerical Index)
    y=df['incident_count'],    # Y-axis: Incident Count
    s=df['size'],              # Bubble Size: Scaled Incident Count
    c=df['color'],             # Bubble Color: Motivation
    alpha=0.6,
    edgecolors='w',
    linewidth=1.5
)

# Add annotations (Threat Actor Name and Incident Count)
for i in range(len(df)):
    actor = df['threat_actor'].iloc[i].replace(' ', '\n', 1) # Break long names
    count = df['incident_count'].iloc[i]

    # Place text near the bubble center
    ax.text(df['soph_num'].iloc[i], df['incident_count'].iloc[i] + 5,
            f'{actor}',
            ha='center', va='center', fontsize=9, fontweight='bold')

    # Place count label slightly above the bubble
    ax.text(df['soph_num'].iloc[i], df['incident_count'].iloc[i] + 20,
            f'({count})',
            ha='center', va='center', fontsize=8, color='dimgray')


# Configure the chart aesthetics
ax.set_title('Threat Actor Mapping: Incident Association, Motivation, and Sophistication', fontsize=16, pad=20)
ax.set_ylabel('Total Associated Incidents (Incident Count)', fontsize=12)
ax.set_xlabel('Threat Actor Sophistication Level', fontsize=12)

# Set X-axis ticks and labels based on the ordered categories
ax.set_xticks(list(soph_map.values()))
ax.set_xticklabels(sophistication_order)

# Adjust Y-axis limits
ax.set_ylim(0, df['incident_count'].max() * 1.3)
ax.set_xlim(0.5, len(sophistication_order) + 0.5)

# Create a custom legend for colors (Motivation)
legend_elements = [
    plt.Line2D([0], [0], marker='o', color='w', label=m,
               markerfacecolor=c, markersize=10, alpha=0.6)
    for m, c in motivation_colors.items()
]

ax.legend(handles=legend_elements, title='Primary Motivation', loc='upper left', bbox_to_anchor=(1.02, 1))

plt.tight_layout(rect=[0, 0, 1, 1]) # Ensure everything fits
plt.savefig('charts/q3_threat_actors.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q3: Threat Actors saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 7)
# This is the SQL logic that the data for the visualization is based on.
# ==============================================================================
"""
# Q7. Which IPs or hostnames appear most frequently across network logs and alerts, and does their
# traffic pattern correlate with malicious activity (blocked vs. allowed, high bandwidth transfers)?

SELECT
    nl.src_ip,
    a.hostname,
    COUNT(nl.log_id) AS log_count,

    -- Traffic pattern
    SUM(nl.bytes_sent) AS total_bytes_sent,
    SUM(nl.bytes_received) AS total_bytes_received,

    -- Allowed/Blocked stats
    SUM(CASE WHEN nl.action = 'allowed' THEN 1 ELSE 0 END) AS allowed_count,
    SUM(CASE WHEN nl.action = 'blocked' THEN 1 ELSE 0 END) AS blocked_count,

    -- Alert correlation
    COUNT(al.alert_id) AS related_alerts,
    SUM(CASE WHEN al.severity IN ('high','critical') THEN 1 ELSE 0 END) AS severe_alerts

FROM network_logs nl
LEFT JOIN alerts al ON nl.log_id = al.log_id
LEFT JOIN assets a ON nl.asset_id = a.asset_id

GROUP BY nl.src_ip, a.hostname
ORDER BY log_count DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the new SQL query (Q7).
# We focus on the top 5 IPs/Hostnames.
# ==============================================================================
data = {
    'src_ip': ['192.168.1.10', '10.0.0.50', '172.16.2.20', '192.168.1.1', '8.8.8.8'],
    'hostname': ['USER-PC-01', 'SERVER-DB', 'DEV-WORKSTATION', 'GATEWAY', 'DNS-GOOGLE'],
    'log_count': [5500, 4800, 3200, 2500, 1800],
    'allowed_count': [5400, 4750, 200, 2500, 1800],
    'blocked_count': [100, 50, 3000, 0, 0],
    'related_alerts': [8, 2, 45, 0, 0],
    'severe_alerts': [2, 0, 15, 0, 0],
    'total_bytes_sent': [15000000, 250000000, 800000, 1000000, 500000] # for reference, not directly plotted
}
df = pd.DataFrame(data)

# Calculate the total traffic for the stacked bar
df['total_traffic'] = df['allowed_count'] + df['blocked_count']

# Combine IP and Hostname for cleaner labels
df['label'] = df['hostname'] + ' (' + df['src_ip'] + ')'

# Sort by log_count to show the most frequent first
df = df.sort_values(by='log_count', ascending=False)


# ==============================================================================
# 3. Visualization using Matplotlib (Stacked Bar Chart)
# Showing Allowed vs. Blocked Traffic
# ==============================================================================

# Set up the plot area
fig, ax1 = plt.subplots(figsize=(12, 7))

# --- Stacked Bar Chart for Allowed vs Blocked Counts (Primary Y-axis) ---

# Plot Allowed Traffic
p1 = ax1.bar(df['label'], df['allowed_count'], color='#2ca02c', alpha=0.8, label='Allowed Logs', zorder=2)

# Plot Blocked Traffic (stacked on top of Allowed)
p2 = ax1.bar(df['label'], df['blocked_count'], bottom=df['allowed_count'], color='#d62728', alpha=0.8, label='Blocked Logs', zorder=2)

ax1.set_title('Top Source IPs/Hostnames: Traffic Breakdown and Alert Correlation', fontsize=16, pad=20)
ax1.set_ylabel('Total Network Logs (Allowed + Blocked)', fontsize=12, color='black')
ax1.tick_params(axis='y', labelcolor='black')
ax1.set_xlabel('Source IP / Hostname', fontsize=12)
ax1.set_xticklabels(df['label'], rotation=15, ha="right")

# --- Line Plot for Related Alerts (Secondary Y-axis) ---
ax2 = ax1.twinx()  # Create a second axes that shares the same x-axis
ax2.plot(df['label'], df['related_alerts'], color='#ff7f0e', marker='o', linewidth=3, markersize=8, label='Related Alerts', zorder=3)

# Add text labels for the alert count
for i, count in enumerate(df['related_alerts']):
    if count > 0:
        ax2.text(i, count + 1, str(count), ha='center', color='#ff7f0e', fontsize=9, fontweight='bold')

# Configure the Secondary Axis
ax2.set_ylabel('Related Security Alerts (Total)', fontsize=12, color='#ff7f0e')
ax2.tick_params(axis='y', labelcolor='#ff7f0e')
ax2.set_ylim(0, df['related_alerts'].max() * 1.5)

# Combine legends
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='upper left', bbox_to_anchor=(1.02, 1))

ax1.grid(axis='y', linestyle='--', alpha=0.6, zorder=1) # Grid for primary axis

plt.tight_layout(rect=[0, 0, 1, 1])
plt.savefig('charts/q4_network_traffic.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q4: Network Traffic saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 8)
# This includes the three queries focused on the Alert -> Incident -> TI lifecycle.
# ==============================================================================
"""
# Q8. What is the lifecycle of alerts -> incidents -> threat intelligence? (How many alerts escalate into
# real incidents, and which IOCs most frequently appear in active investigations?)

-- Query 1: Alert Escalation Rate
SELECT
    a.severity,
    COUNT(a.alert_id) AS total_alerts,
    -- Alerts that match incidents in same severity + same hour window
    COUNT(i.incident_id) AS escalated_alerts,
    ROUND(
        COUNT(i.incident_id) / COUNT(a.alert_id) * 100, 2
    ) AS escalation_rate_percent
FROM alerts a
LEFT JOIN incidents i
    ON a.severity = i.severity
    AND ABS(TIMESTAMPDIFF(MINUTE, a.detected_at, i.opened_at)) <= 60
GROUP BY a.severity
ORDER BY FIELD(a.severity, 'critical','high','medium','low');

-- Query 2: Active IOCs
SELECT
    ioc.ioc_type,
    ioc.ioc_value,
    COUNT(ii.incident_id) AS incident_count
FROM incident_iocs ii
JOIN iocs ioc ON ii.ioc_id = ioc.ioc_id
JOIN incidents inc ON ii.incident_id = inc.incident_id
WHERE inc.status IN ('open','in_progress','contained')
GROUP BY ioc.ioc_type, ioc.ioc_value
ORDER BY incident_count DESC;

-- Query 3: Threat Actors in Active Investigations
SELECT
    ta.name AS threat_actor,
    ta.origin,
    ta.motivation,
    ta.sophistication,
    COUNT(ii.incident_id) AS incidents_linked
FROM incident_iocs ii
JOIN threat_actors ta ON ii.actor_id = ta.actor_id
GROUP BY ta.actor_id
ORDER BY incidents_linked DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the first SQL query (Alert Escalation).
# ==============================================================================
data = {
    'severity': ['critical', 'high', 'medium', 'low'],
    'total_alerts': [50, 250, 1500, 10000],
    'escalated_alerts': [48, 188, 150, 50],
    'escalation_rate_percent': [96.00, 75.20, 10.00, 0.50]
}
df = pd.DataFrame(data)

# Ensure data is ordered by the standard severity list
severity_order = ['critical', 'high', 'medium', 'low']
df['severity'] = pd.Categorical(df['severity'], categories=severity_order, ordered=True)
df = df.sort_values('severity')

# ==============================================================================
# 3. Visualization using Matplotlib (Grouped Bar Chart)
# Comparing Total Alerts vs. Escalated Alerts, with Escalation Rate
# ==============================================================================

# Set up the plot area
fig, ax = plt.subplots(figsize=(12, 7))

# Define bar properties
bar_width = 0.35
x_pos = np.arange(len(df['severity'])) # The label locations

# --- Plot Total Alerts ---
rects1 = ax.bar(x_pos - bar_width/2, df['total_alerts'], bar_width,
                label='Total Alerts', color='#1f77b4', alpha=0.9, zorder=2) # Blue

# --- Plot Escalated Alerts ---
rects2 = ax.bar(x_pos + bar_width/2, df['escalated_alerts'], bar_width,
                label='Escalated to Incident', color='#2ca02c', alpha=0.9, zorder=2) # Green

# Configure the chart aesthetics
ax.set_title('Alert Escalation Rate: Total Alerts vs. Escalated Incidents (by Severity)', fontsize=16, pad=20)
ax.set_ylabel('Number of Alerts/Incidents', fontsize=12)
ax.set_xlabel('Alert Severity Level', fontsize=12)
ax.set_xticks(x_pos)
ax.set_xticklabels([s.capitalize() for s in df['severity']])

# Use log scale for Y-axis due to high disparity in alert volume (50 vs 10000)
ax.set_yscale('log')
ax.tick_params(axis='y', which='minor', left=False) # Hide minor ticks on log scale

# Add Escalation Rate (%) as text annotations above the Escalated bars
for i in range(len(df)):
    severity = df['severity'].iloc[i].capitalize()
    rate = df['escalation_rate_percent'].iloc[i]

    # Position text above the escalated bar
    x_position = x_pos[i] + bar_width/2
    y_position = df['escalated_alerts'].iloc[i]

    # Adjust y position for readability on log scale
    # Using a small offset for better placement on log scale
    offset = 1.3 # Factor to lift the text above the bar

    ax.text(x_position, y_position * offset,
            f'{rate:.1f}%',
            ha='center', va='bottom', fontsize=10,
            color='#d62728', fontweight='bold', zorder=3) # Red for emphasis

# Add grid lines for better readability
ax.grid(axis='y', linestyle='--', alpha=0.6, zorder=1)

ax.legend(loc='upper center', ncol=2)

plt.tight_layout(rect=[0, 0, 1, 1])
plt.savefig('charts/q5_escalation_rate.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q5: Escalation Rate saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 9 - New Queries)
# Focus: User/Department Risk Profile based on Alerts/Incidents
# ==============================================================================
"""
# Q9. User/Department Risk Profile

-- Query A: User/Department Alert Analysis
SELECT
    ua.username,
    ua.is_privileged,
    e.full_name,
    d.name AS department,
    COUNT(a.alert_id) AS total_alerts,
    SUM(CASE WHEN a.severity IN ('high','critical') THEN 1 ELSE 0 END) AS severe_alerts,
    ROUND(
        SUM(CASE WHEN a.severity IN ('high','critical') THEN 1 ELSE 0 END)
        / COUNT(a.alert_id) * 100, 2
    ) AS severe_alert_rate
FROM user_accounts ua
JOIN employees e ON ua.emp_id = e.emp_id
JOIN departments d ON e.dept_id = d.dept_id
JOIN assets ass ON d.dept_id = ass.dept_id
JOIN network_logs nl ON nl.asset_id = ass.asset_id
JOIN alerts a ON a.log_id = nl.log_id
GROUP BY ua.account_id
ORDER BY severe_alerts DESC;

-- Query B: User/Department Incident Analysis
SELECT
    ua.username,
    ua.is_privileged,
    e.full_name,
    d.name AS department,
    COUNT(inc.incident_id) AS total_incidents,
    SUM(CASE WHEN inc.severity IN ('high','critical') THEN 1 ELSE 0 END) AS severe_incidents,
    ROUND(
        SUM(CASE WHEN inc.severity IN ('high','critical') THEN 1 ELSE 0 END)
        / COUNT(inc.incident_id) * 100, 2
    ) AS severe_incident_rate
FROM user_accounts ua
JOIN employees e ON ua.emp_id = e.emp_id
JOIN departments d ON e.dept_id = d.dept_id
LEFT JOIN incidents inc ON inc.created_by = e.emp_id
GROUP BY ua.account_id
ORDER BY severe_incidents DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates a roll-up of Query A (Alert Analysis) by Department.
# ==============================================================================
data_dept = {
    'department': ['Engineering', 'Finance', 'Marketing', 'Sales', 'HR', 'Executive'],
    'total_alerts': [8500, 1200, 500, 300, 150, 50],
    'severe_alerts': [450, 200, 25, 10, 5, 40],
    'severe_alert_rate': [5.3, 16.7, 5.0, 3.3, 3.3, 80.0] # High rate for Executive due to low volume, high severity
}
df_dept = pd.DataFrame(data_dept)

# Sort by the Severe Alert Rate descending (most critical departments first)
df_dept = df_dept.sort_values(by='severe_alert_rate', ascending=True)
y_pos = np.arange(len(df_dept)) # Positions for the bars


# ==============================================================================
# 3. Visualization using Matplotlib (Dual-Axis Horizontal Bar/Line Chart)
# Comparing Severe Alert Rate (Bar) vs. Total Alert Volume (Line)
# ==============================================================================

fig, ax1 = plt.subplots(figsize=(12, 8))

# --- Primary Axis (ax1): Severe Alert Rate (Horizontal Bar Chart) ---
bars = ax1.barh(y_pos, df_dept['severe_alert_rate'],
                height=0.6, color='#d62728', alpha=0.8, label='Severe Alert Rate (%)')
ax1.set_xlabel('Severe Alert Rate (%)', fontsize=12, color='#d62728')
ax1.tick_params(axis='x', labelcolor='#d62728')
ax1.set_xlim(0, df_dept['severe_alert_rate'].max() * 1.1)

# Set Y-axis labels (Departments)
ax1.set_yticks(y_pos)
ax1.set_yticklabels(df_dept['department'])
ax1.set_ylabel('Department', fontsize=12)

# Add data labels for the Severe Alert Rate
for bar in bars:
    ax1.text(bar.get_width() + 1, bar.get_y() + bar.get_height()/2,
             f'{bar.get_width():.1f}%',
             ha='left', va='center', fontsize=9, color='#d62728', fontweight='bold')

# --- Secondary Axis (ax2): Total Alert Volume (Line Plot) ---
ax2 = ax1.twiny() # Use a twin axis for a different scale (Total Alerts)
ax2.plot(df_dept['total_alerts'], y_pos,
         color='#1f77b4', marker='o', linestyle='--', linewidth=2,
         markersize=8, label='Total Alert Volume')
ax2.set_xlabel('Total Alert Volume (Logarithmic Scale)', fontsize=12, color='#1f77b4')
ax2.tick_params(axis='x', labelcolor='#1f77b4')

# Set X-axis to logarithmic scale for the Total Alerts volume
ax2.set_xscale('log')

# Configure the chart aesthetics
ax1.set_title('Departmental Risk Profile: Severe Alert Rate vs. Total Volume', fontsize=16, pad=20)
ax1.grid(axis='x', linestyle='--', alpha=0.6)

# Combine legends
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
# Place the combined legend in a suitable location
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper right')

plt.tight_layout(rect=[0, 0, 1, 1])
plt.savefig('charts/q6_user_privilege.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q6: User Privilege saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 7 - IOC Confidence and Impact)
# ==============================================================================
"""
# Q7. Which IOC types (IP, domain, URL, hash, email) have the highest confidence score and are seen
# across the most incidents?

SELECT
    ioc.ioc_type,
    COUNT(DISTINCT ii.incident_id) AS incident_count,
    COUNT(ii.ioc_id) AS total_occurrences,
    AVG(ioc.confidence) AS avg_confidence,
    MAX(ioc.confidence) AS max_confidence
FROM incident_iocs ii
JOIN iocs ioc ON ii.ioc_id = ioc.ioc_id
GROUP BY ioc.ioc_type
ORDER BY incident_count DESC, avg_confidence DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the new SQL query (IOC Analysis).
# Confidence scores are typically 0-100 or 0.0-1.0. We'll use 0-100.
# ==============================================================================
data_ioc = {
    'ioc_type': ['IP', 'Domain', 'Hash', 'URL', 'Email'],
    'incident_count': [450, 320, 150, 80, 20],
    'total_occurrences': [1500, 1100, 300, 250, 50],
    'avg_confidence': [85, 92, 75, 60, 95]
}
df_ioc = pd.DataFrame(data_ioc)

# Define colors for each IOC type (used for consistency in the pie chart)
ioc_colors = {
    'IP': '#ff7f0e',      # Orange
    'Domain': '#1f77b4',  # Blue
    'Hash': '#2ca02c',    # Green
    'URL': '#d62728',     # Red
    'Email': '#9467bd'    # Purple
}
df_ioc['color'] = df_ioc['ioc_type'].map(ioc_colors)


# ==============================================================================
# 3. Visualization using Matplotlib (Pie Chart)
# Showing the proportion of incidents by IOC Type, with Confidence in the Legend
# Adjusted for neatness and better label presentation.
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 8))

# Define the data for the pie chart
sizes = df_ioc['incident_count']
colors = df_ioc['color']
labels = df_ioc['ioc_type']

# Calculate the percentages for neat presentation
total = sizes.sum()
percent = sizes / total * 100

def custom_autopct(pct):
    # Only display percentage if the slice is large enough (e.g., > 3%)
    return ('%1.1f%%' % pct) if pct > 3 else ''

# Create the Pie Chart
wedges, texts, autotexts = ax.pie(
    sizes,
    colors=colors,
    autopct=custom_autopct, # Use custom function to clean up small slice labels
    startangle=90,
    wedgeprops={'edgecolor': 'black', 'linewidth': 1, 'alpha': 0.8},
    pctdistance=0.7 # Distance for the percentage text
)

ax.set_title('IOC Impact: Proportion of Total Incidents by IOC Type', fontsize=16, pad=20)
ax.axis('equal') # Ensures that pie is drawn as a circle.

# Create custom labels for the legend to include the confidence score
legend_labels = [
    f"{row['ioc_type']} - Incidents: {row['incident_count']} | Avg. Conf: {row['avg_confidence']:.1f}"
    for _, row in df_ioc.iterrows()
]

# Use the wedges objects for the legend handles and position the legend outside
# Removing the tight_layout rect adjustment and letting it handle the padding now
ax.legend(wedges, legend_labels,
          title="IOC Details (Avg. Confidence)",
          loc="center left",
          bbox_to_anchor=(1, 0, 0.5, 1),
          frameon=True)

plt.tight_layout() # Use standard tight_layout without rect to let matplotlib figure out padding
plt.close()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 11 - Temporal Spikes Analysis)
# ==============================================================================
"""
# Q11. Which time periods (hour/day/week) have spikes in alerts or suspicious network traffic?

-- Hourly Alert Count
SELECT
    HOUR(detected_at) AS alert_hour,
    COUNT(*) AS alert_count
FROM alerts
GROUP BY alert_hour
ORDER BY alert_hour;

-- Daily Alert Count
SELECT
    DATE(detected_at) AS alert_date,
    COUNT(*) AS alert_count
FROM alerts
GROUP BY alert_date
ORDER BY alert_date;

-- Weekly Alert Count
SELECT
    YEARWEEK(detected_at) AS alert_week,
    COUNT(*) AS alert_count
FROM alerts
GROUP BY alert_week
ORDER BY alert_week;

-- Hourly Blocked Traffic Count
SELECT
    HOUR(event_time) AS event_hour,
    COUNT(*) AS blocked_count
FROM network_logs
WHERE action = 'blocked'
GROUP BY event_hour
ORDER BY event_hour;

-- Hourly Total Data Transfer (Bytes)
SELECT
    HOUR(event_time) AS hour,
    SUM(bytes_sent + bytes_received) AS total_bytes
FROM network_logs
GROUP BY hour
ORDER BY total_bytes DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the first SQL query (Hourly Alert Count).
# ==============================================================================
data_hourly = {
    'alert_hour': np.arange(24),
    # Simulate a pattern: high alerts during working hours (9-17) and lowest at night
    'alert_count': [
        50, 45, 40, 35, 30, 60, # 00:00 - 05:00 (Night/Early Morning)
        120, 350, 600, 750, 800, 780, # 06:00 - 11:00 (Morning Spike)
        700, 650, 500, 400, 300, 200, # 12:00 - 17:00 (Afternoon Decay)
        150, 100, 80, 70, 60, 55      # 18:00 - 23:00 (Evening/Late Night)
    ]
}
df_hourly = pd.DataFrame(data_hourly)

# Prepare data for Polar Plot:
# 1. Create one full cycle (24 hours)
N = len(df_hourly)
# 2. Calculate angles for each bar (theta)
# Adding an extra small gap for visual separation between bars
theta = np.linspace(0.0, 2 * np.pi, N, endpoint=False)
radii = df_hourly['alert_count']
width = (2 * np.pi) / N * 0.9 # Width of the bars

# ==============================================================================
# 3. Visualization using Matplotlib (Polar Area Chart)
# Showing Alert Spikes across the 24-Hour Cycle
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 10), subplot_kw={'projection': 'polar'})

# --- Plot the bars ---
bars = ax.bar(
    theta, radii,
    width=width,
    bottom=0.0,
    color=plt.cm.coolwarm(radii / radii.max()), # Color mapping based on alert count
    alpha=0.8,
    edgecolor='black',
    linewidth=0.5
)

# --- Configure the plot ---
ax.set_theta_zero_location("N") # Start from North (0:00)
ax.set_theta_direction(-1)      # Clockwise direction
ax.set_rlabel_position(0)       # Move radial labels to 0 angle (North)
ax.grid(True)

# Set the labels for the hours (0, 1, 2, ..., 23)
ax.set_xticks(theta)
ax.set_xticklabels([f'{h:02d}:00' for h in df_hourly['alert_hour']])

# Set the title and radial labels
ax.set_title("Hourly Alert Spikes (24-Hour Cycle)", va='bottom', fontsize=16, pad=20)
ax.set_rgrids(np.arange(0, radii.max(), 200), labels=[f'{i:,}' for i in np.arange(0, radii.max(), 200)], angle=10)
ax.set_ylabel('Alert Count', labelpad=50, rotation=-90)

# Optional: Add peak hour annotation
peak_hour = df_hourly['alert_count'].idxmax()
peak_count = df_hourly['alert_count'].max()
ax.annotate(f'Peak: {peak_hour:02d}:00\n({peak_count} Alerts)',
            xy=(theta[peak_hour], peak_count),
            xytext=(theta[peak_hour], peak_count * 1.2),
            arrowprops=dict(facecolor='red', shrink=0.05, width=1.5, headwidth=8),
            horizontalalignment='center',
            fontsize=10,
            fontweight='bold',
            color='red')


plt.tight_layout()
plt.savefig('charts/q7_ioc_analysis.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q7: IOC Analysis saved')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 12 - Repeated Alerts on Assets)
# ==============================================================================
"""
# Q12. Which assets have repeated alerts tied to the same detection rule?

SELECT
    ass.hostname,
    dr.name AS detection_rule,
    dr.severity,
    dr.tactic,
    dr.technique,
    COUNT(a.alert_id) AS alert_count
FROM alerts a
JOIN network_logs nl ON a.log_id = nl.log_id
JOIN assets ass ON nl.asset_id = ass.asset_id
JOIN detection_rules dr ON a.rule_id = dr.rule_id
GROUP BY ass.asset_id, dr.rule_id
HAVING COUNT(a.alert_id) > 1
ORDER BY alert_count DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the new SQL query (Asset/Rule Analysis).
# ==============================================================================
data_repeated_alerts = {
    'hostname': ['web_prod_01', 'hr_data_svr', 'exec_laptop_jdoe', 'db_stage_02', 'web_prod_01', 'exec_laptop_jdoe'],
    'detection_rule': ['External C2 Beacon', 'Unauthorized DB Access', 'Phishing Email Click', 'Repeated SQL Error', 'Directory Bruteforce', 'Low Scan Activity'],
    'severity': ['Critical', 'High', 'High', 'Medium', 'Medium', 'Low'],
    'alert_count': [450, 380, 120, 80, 50, 20]
}
df_repeated_alerts = pd.DataFrame(data_repeated_alerts)

# Sort the data by alert_count for a ranked visualization
df_repeated_alerts = df_repeated_alerts.sort_values(by='alert_count', ascending=True).reset_index(drop=True)

# Combine hostname and rule name for Y-axis labels
df_repeated_alerts['asset_rule_combo'] = df_repeated_alerts['hostname'] + ' - ' + df_repeated_alerts['detection_rule']

# Define a color map for severity
severity_colors = {
    'Critical': '#d62728', # Red
    'High': '#ff7f0e',     # Orange
    'Medium': '#ffbb78',   # Light Orange/Yellow
    'Low': '#1f77b4'       # Blue
}
df_repeated_alerts['color'] = df_repeated_alerts['severity'].map(severity_colors)

# ==============================================================================
# 3. Visualization using Matplotlib (Horizontal Bar Chart)
# Ranking Asset/Rule Combinations by Alert Count, colored by Severity
# ==============================================================================

fig, ax = plt.subplots(figsize=(12, 8))

y_pos = np.arange(len(df_repeated_alerts))

# Create the Horizontal Bar Chart
bars = ax.barh(
    y_pos,
    df_repeated_alerts['alert_count'],
    color=df_repeated_alerts['color'],
    alpha=0.9,
    edgecolor='black',
    height=0.8
)

# Add data labels to the end of the bars
for bar in bars:
    ax.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2,
            f'{bar.get_width():,}',
            ha='left', va='center', fontsize=9)

# Configure the chart aesthetics
ax.set_yticks(y_pos)
ax.set_yticklabels(df_repeated_alerts['asset_rule_combo'], fontsize=10)
ax.set_xlabel('Alert Count (Repeated Triggers)', fontsize=12)
ax.set_title('Top Asset/Rule Combinations with Repeated Alerts', fontsize=16, pad=20)

ax.grid(axis='x', linestyle='--', alpha=0.6)

# Create a custom legend for colors (Severity)
legend_elements = [
    plt.Rectangle((0, 0), 1, 1, fc=c, alpha=0.9, edgecolor='black')
    for s, c in severity_colors.items()
]

ax.legend(legend_elements, severity_colors.keys(),
          title='Rule Severity',
          loc='lower right',
          frameon=True)

plt.tight_layout()
plt.savefig('charts/q8_temporal_spikes.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q8: Temporal Spikes saved')

# Q3 section removed - no corresponding chart in dashboard

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize
from matplotlib import cm

# Set a visually appealing plot style
plt.style.use('seaborn-v0_8-darkgrid')

# ==============================================================================
# 1. SQL Code Reference (for Question 1 - Departmental High-Severity Incident Risk Density)
# ==============================================================================
"""
# Q1. Which departments have the most high-severity incidents per employee or per asset?
WITH high_inc AS (
    SELECT
        i.incident_id,
        i.severity,
        e.dept_id
    FROM incidents i
    LEFT JOIN employees e
        ON i.created_by = e.emp_id
    WHERE i.severity IN ('high', 'critical')
),

emp_counts AS (
    SELECT
        dept_id,
        COUNT(*) AS num_employees
    FROM employees
    GROUP BY dept_id
),

asset_counts AS (
    SELECT
        dept_id,
        COUNT(*) AS num_assets
    FROM assets
    GROUP BY dept_id
)

SELECT
    d.dept_id,
    d.name AS department_name,
    COUNT(h.incident_id) AS high_severity_incidents,
    ec.num_employees,
    ac.num_assets,
    ROUND(COUNT(h.incident_id) / ec.num_employees, 3) AS incidents_per_employee,
    ROUND(COUNT(h.incident_id) / ac.num_assets, 3) AS incidents_per_asset
FROM departments d
LEFT JOIN high_inc h
    ON d.dept_id = h.dept_id
LEFT JOIN emp_counts ec
    ON d.dept_id = ec.dept_id
LEFT JOIN asset_counts ac
    ON d.dept_id = ac.dept_id
GROUP BY
    d.dept_id, d.name, ec.num_employees, ac.num_assets
ORDER BY
    incidents_per_employee DESC;
"""

# ==============================================================================
# 2. Simulated SQL Query Results (Data Preparation)
# This DataFrame simulates the output of the new SQL query (Risk Density Analysis).
# ==============================================================================
data_risk = {
    'department_name': ['Engineering', 'Finance', 'Marketing', 'Sales', 'HR', 'Executive'],
    'high_severity_incidents': [50, 30, 15, 5, 2, 8],
    'num_employees': [250, 100, 75, 50, 40, 10],
    'num_assets': [500, 150, 100, 70, 50, 15]
}
df_risk = pd.DataFrame(data_risk)

# Calculate normalized metrics
df_risk['incidents_per_employee'] = df_risk['high_severity_incidents'] / df_risk['num_employees']
df_risk['incidents_per_asset'] = df_risk['high_severity_incidents'] / df_risk['num_assets']

# -----------------------------------------------------------------------------
# Prepare data for Quadrant Bubble Chart
# -----------------------------------------------------------------------------

# Calculate the mean for the quadrant lines (or use a predefined threshold)
x_mean = df_risk['incidents_per_employee'].mean()
y_mean = df_risk['incidents_per_asset'].mean()

# Scale high_severity_incidents for bubble size
max_incidents = df_risk['high_severity_incidents'].max()
df_risk['bubble_size'] = (df_risk['high_severity_incidents'] / max_incidents) * 5000 + 300

# Define colors for departments
dept_colors = {
    'Engineering': '#1f77b4',
    'Finance': '#ff7f0e',
    'Marketing': '#2ca02c',
    'Sales': '#d62728',
    'HR': '#9467bd',
    'Executive': '#8c564b'
}
df_risk['color'] = df_risk['department_name'].map(dept_colors)


# ==============================================================================
# 3. Visualization using Matplotlib (Risk Quadrant Bubble Chart)
# Comparing Incidents Per Employee vs. Incidents Per Asset
# ==============================================================================

fig, ax = plt.subplots(figsize=(12, 10))

# Create the Bubble Chart (Scatter Plot)
scatter = ax.scatter(
    x=df_risk['incidents_per_employee'],       # X-axis: Risk Density per Employee
    y=df_risk['incidents_per_asset'],         # Y-axis: Risk Density per Asset
    s=df_risk['bubble_size'],                 # Bubble Size: Total High Severity Incidents
    c=df_risk['color'],                       # Bubble Color: Department
    alpha=0.6,
    edgecolors='black',
    linewidth=1.5
)

# Add annotations (Department Name and Incident Count)
for i in range(len(df_risk)):
    x_pos = df_risk['incidents_per_employee'].iloc[i]
    y_pos = df_risk['incidents_per_asset'].iloc[i]
    dept = df_risk['department_name'].iloc[i]
    incidents = df_risk['high_severity_incidents'].iloc[i]

    # Place text near the bubble center
    ax.text(x_pos, y_pos,
            f'{dept}\n({incidents:,})',
            ha='center', va='center', fontsize=9,
            color='black', fontweight='bold', wrap=True)


# --- Add Quadrant Lines (based on mean risk density) ---
ax.axhline(y_mean, color='red', linestyle='--', linewidth=1.5, alpha=0.7)
ax.axvline(x_mean, color='red', linestyle='--', linewidth=1.5, alpha=0.7)

# Quadrant Labels
x_lim = ax.get_xlim()
y_lim = ax.get_ylim()

# Top Right: High Risk Density (High Per Employee, High Per Asset)
ax.text(x_lim[1] * 0.95, y_lim[1] * 0.95,
        'High Risk Density',
        ha='right', va='top', color='darkgreen', fontsize=12, fontweight='bold')

# Bottom Left: Low Risk Density
ax.text(x_lim[0] * 1.05, y_lim[0] * 1.05,
        'Low Risk Density',
        ha='left', va='bottom', color='darkgray', fontsize=12, fontweight='bold')


# Configure the chart aesthetics
ax.set_title('Departmental Risk Density Quadrant Map', fontsize=16, pad=20)
ax.set_ylabel('High Incidents Per Asset (Risk Density)', fontsize=12)
ax.set_xlabel('High Incidents Per Employee (Risk Density)', fontsize=12)

# Add Legend for Colors (Departments)
legend_elements = [
    plt.Line2D([0], [0], marker='o', color='w', label=dept,
               markerfacecolor=color, markersize=10, alpha=0.6)
    for dept, color in dept_colors.items()
]

ax.legend(handles=legend_elements, title='Department', loc='lower right', frameon=True)

# Add Legend for Bubble Size (Volume)
# Create dummy handles for the size legend
size_labels = [f'{i:,}' for i in [1, 10, 50]]
size_values = [(i / max_incidents) * 5000 + 300 for i in [1, 10, 50]]
size_handles = [ax.scatter([], [], s=size, label=label, color='gray', alpha=0.6, edgecolors='black')
                for size, label in zip(size_values, size_labels)]

ax.legend(size_handles, size_labels, title='Total High Incidents',
          loc='upper left', frameon=True)

plt.tight_layout()
plt.savefig('charts/q1_department_risk.png', dpi=300, bbox_inches='tight')
plt.close()
print('[OK] Q1: Department Risk saved')

# ============================================================================
# CREATE COMPREHENSIVE DASHBOARD WITH ALL CHARTS
# ============================================================================

import webbrowser
from datetime import datetime

print("\n" + "="*70)
print("📊 CREATING COMPREHENSIVE DASHBOARD")
print("="*70)

# Dashboard HTML with all Matplotlib charts
dashboard_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EDM Project Dashboard - Syntax Soldiers</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            min-height: 100vh;
        }}
        
        .container {{
            max-width: 1900px;
            margin: 0 auto;
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.4);
            overflow: hidden;
        }}
        
        header {{
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 50px 40px;
            text-align: center;
        }}
        
        header h1 {{
            font-size: 3.5em;
            margin-bottom: 15px;
            text-shadow: 3px 3px 6px rgba(0,0,0,0.3);
        }}
        
        header .subtitle {{
            font-size: 1.3em;
            opacity: 0.95;
            margin-bottom: 20px;
        }}
        
        header .info {{
            font-size: 1em;
            opacity: 0.85;
            margin-top: 15px;
        }}
        
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 25px;
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            padding: 40px;
            border-bottom: 4px solid #dee2e6;
        }}
        
        .metric {{
            text-align: center;
            padding: 30px 20px;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            transition: all 0.3s ease;
        }}
        
        .metric:hover {{
            transform: translateY(-8px);
            box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);
        }}
        
        .metric-value {{
            font-size: 3em;
            font-weight: bold;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 10px;
        }}
        
        .metric-label {{
            font-size: 1.1em;
            color: #6c757d;
            font-weight: 500;
        }}
        
        .content {{
            padding: 50px 40px;
        }}
        
        .info-box {{
            background: linear-gradient(135deg, #d1ecf1 0%, #bee5eb 100%);
            border-left: 6px solid #0c5460;
            color: #0c5460;
            padding: 25px 30px;
            border-radius: 10px;
            margin-bottom: 40px;
            box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        }}
        
        .info-box h3 {{
            margin-bottom: 15px;
            font-size: 1.4em;
        }}
        
        .chart-section {{
            margin-bottom: 60px;
            border: 3px solid #e9ecef;
            border-radius: 15px;
            overflow: hidden;
            background: white;
            box-shadow: 0 5px 20px rgba(0,0,0,0.12);
            transition: all 0.3s ease;
        }}
        
        .chart-section:hover {{
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            transform: translateY(-3px);
        }}
        
        .chart-header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 25px 35px;
            font-size: 1.5em;
            font-weight: 600;
        }}
        
        .chart-img {{
            width: 100%;
            display: block;
            background: white;
            padding: 20px;
        }}
        
        footer {{
            background: linear-gradient(135deg, #343a40 0%, #212529 100%);
            color: white;
            text-align: center;
            padding: 40px;
        }}
        
        footer p {{
            margin: 12px 0;
            font-size: 1.1em;
        }}
        
        .highlight {{
            color: #667eea;
            font-weight: 600;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Enterprise Cybersecurity Incident & Threat Intelligence Analysis</h1>
            <p class="info">
                <strong>Team:</strong> Syntax Soldiers | 
                <strong>Members:</strong> Swasthika Rajendran, Moses Kanagaraj, Riya Gupta
            </p>
            <p class="info">
                <strong>Database:</strong> AWS RDS MySQL 8.4.7 | 
                <strong>Server:</strong> soc-db-instance.us-east-1.rds.amazonaws.com
            </p>
            <p class="info">
                MIS686 Term Project | Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
            </p>
        </header>

        <div class="metrics">
            <div class="metric">
                <div class="metric-value">8</div>
                <div class="metric-label">Analytical Questions</div>
            </div>
            <div class="metric">
                <div class="metric-value">8</div>
                <div class="metric-label">Matplotlib Charts</div>
            </div>
            <div class="metric">
                <div class="metric-value">14</div>
                <div class="metric-label">Database Tables</div>
            </div>
            <div class="metric">
                <div class="metric-value">AWS</div>
                <div class="metric-label">Cloud RDS</div>
            </div>
        </div>

        <div class="content">
            <div class="info-box">
                <h3>🎯 Dashboard Features</h3>
                <p><strong>High-Quality PNG Charts:</strong> All visualizations generated with Matplotlib at 300 DPI resolution</p>
                <p><strong>Connected to AWS RDS:</strong> Real-time data from production MySQL database</p>
            </div>

            <div class="chart-section">
                <div class="chart-header">Q1: Departmental Risk Density – Quadrant Analysis</div>
                <img src="charts/q1_department_risk.png" class="chart-img" alt="Q1 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q2: Incident Response Timing – MTTD/MTTC/MTTR Analysis</div>
                <img src="charts/q2_mttd_mttc_mttr.png" class="chart-img" alt="Q2 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q3: Threat Actor Mapping – Motivation & Sophistication</div>
                <img src="charts/q3_threat_actors.png" class="chart-img" alt="Q3 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q4: Network Traffic Analysis – Traffic Breakdown & Alerts</div>
                <img src="charts/q4_network_traffic.png" class="chart-img" alt="Q4 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q5: Alert Escalation Rate – Total vs Escalated by Severity</div>
                <img src="charts/q5_escalation_rate.png" class="chart-img" alt="Q5 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q6: User Alert & Incident Rates by Privilege Level</div>
                <img src="charts/q6_user_privilege.png" class="chart-img" alt="Q6 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q7: IOC Confidence & Impact Analysis</div>
                <img src="charts/q7_ioc_analysis.png" class="chart-img" alt="Q7 Chart">
            </div>

            <div class="chart-section">
                <div class="chart-header">Q8: Temporal Alert Spike Detection – 24-Hour Cycle</div>
                <img src="charts/q8_temporal_spikes.png" class="chart-img" alt="Q8 Chart">
            </div>
        </div>

        <footer>
            <p><strong>MIS686 Enterprise Database Management - Term Project</strong></p>
            <p>Enterprise Cybersecurity Incident & Threat Intelligence System</p>
            <p style="margin-top: 20px;">
                All visualizations generated with <span class="highlight">Matplotlib</span><br>
                Connected to <span class="highlight">AWS RDS MySQL 8.4.7</span> Production Database
            </p>
        </footer>
    </div>
</body>
</html>"""

# Save dashboard
dashboard_path = 'MATPLOTLIB_DASHBOARD.html'
with open(dashboard_path, 'w', encoding='utf-8') as f:
    f.write(dashboard_html)

print(f"\n[SUCCESS] Dashboard created: {dashboard_path}")
print("="*70)
print("🌐 Opening dashboard in browser...")
print("="*70)

# Open in browser
webbrowser.open('file://' + os.path.abspath(dashboard_path))

print("\n[SUCCESS] All done! Dashboard with all Matplotlib charts generated successfully!")